language: php

php:
  - 5.4

before_script:
  - composer self-update
  - sh -c 'if [ "${TRAVIS_PHP_VERSION}" != "hhvm" ]; then echo "memory_limit = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi;'
  - composer install --ignore-platform-reqs


script: phpunit
